// SPDX-License-Identifier: GPL-3.0-or-later
//
// Build script for the consolidated engine crate.
//
// It exists for one port: huffman.  engine/hexenworld/shared/huffman.c takes
// its frequency table from engine/hexenworld/shared/hufffreq.h, which is a
// comma-separated list of decimal floats wrapped in C comments and included
// as the initialiser of `static const float HuffFreq[256]`.  Those 256 values
// decide the shape of the Huffman tree -- BuildTree compares them with `<`,
// so one differing float can change tie-breaking and therefore every encoded
// byte -- and they are the one thing in this port that cannot be checked by
// reading C.
//
// So the header stays the single source of truth: this script parses it and
// emits the array into OUT_DIR, and the differential harness additionally
// compares the emitted values against the C's table bit for bit.  A build
// script rather than a transcription removes the transcription question, and
// the harness check is what catches a bug in the *parser*.
//
// The emitted literals keep the header's decimal digits verbatim, so rustc
// rounds decimal -> f32 exactly as the C compiler rounds decimal -> float.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let header = Path::new(&manifest_dir).join("../hexenworld/shared/hufffreq.h");
    println!("cargo:rerun-if-changed={}", header.display());

    let source = fs::read_to_string(&header)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", header.display()));

    // Strip /* ... */ comments: the header carries the table's own history in
    // a commented-out block ahead of the live values, and that block has the
    // same shape as the real one.
    let mut stripped = String::with_capacity(source.len());
    let mut in_comment = false;
    let mut chars = source.chars().peekable();
    while let Some(c) = chars.next() {
        if in_comment {
            if c == '*' && chars.peek() == Some(&'/') {
                chars.next();
                in_comment = false;
            }
        } else if c == '/' && chars.peek() == Some(&'*') {
            chars.next();
            in_comment = true;
            // A comment becomes one space, never nothing.  Splicing the two
            // halves of a literal back together would turn
            // `0.14473/*x*/691` into a different, valid-looking number, and
            // the digit check below would not notice.
            stripped.push(' ');
        } else {
            stripped.push(c);
        }
    }
    assert!(!in_comment, "unterminated comment in {}", header.display());

    let values: Vec<&str> = stripped
        .split(',')
        .map(|v| v.trim())
        .filter(|v| !v.is_empty())
        .collect();

    assert_eq!(
        values.len(),
        256,
        "{}: expected 256 frequency values, found {}",
        header.display(),
        values.len()
    );

    // The header must stay plain decimal: no exponent, no hex, no `f`
    // suffix, no sign.  That is what makes the literal safe to copy verbatim
    // into Rust, where `0x1p3` and `1.0e-3` would not be spelled the same way.
    for v in &values {
        let ok = v.starts_with("0.")
            && v.len() >= 3
            && v[2..].bytes().all(|b| b.is_ascii_digit());
        assert!(ok, "{}: {:?} is not a plain decimal literal", header.display(), v);
    }

    let mut out = String::new();
    out.push_str(
        "// Generated by build.rs from engine/hexenworld/shared/hufffreq.h.\n\
         // Do not edit: the header is the source of truth, and\n\
         // engine/rust/huffman/tests/diff_harness.c compares this table\n\
         // against the C's `static const float HuffFreq[256]` bit for bit.\n\
         pub(crate) const HUFF_FREQ: [f32; 256] = [\n",
    );
    for v in &values {
        out.push_str(&format!("    {}f32,\n", v));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("hufffreq.rs"), out).expect("write hufffreq.rs");
}