#!/usr/bin/env python3
"""Generate engine/h2shared/hw_strings_data.h from gamecode/res/*/strings.txt.

HexenWorld's and Siege's string tables are compiled into the engine so a
legacy install -- retail data1 + hw/pak4.pak, nothing else -- prints the
right obituaries on the client and does not stop hwsv's gamecode on them
(GitHub #214).  No pak ships these tables and no manual install step may be
required.  An installed or bundled copy still wins (Host_LoadHWStrings);
this is the last resort.

The engine's nix source filter excludes gamecode/ on purpose, so the table
is generated into the tree rather than at build time.  Keep it in sync:

    python3 scripts/gen_hw_strings.py           # rewrite the header
    python3 scripts/gen_hw_strings.py --check   # exit 1 if it is stale (CI)
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "engine", "h2shared", "hw_strings_data.h")
TABLES = [("hw", "hw_strings_hw"), ("siege", "hw_strings_siege")]


def c_literal_lines(data):
    """One C string literal per source line, adjacent literals concatenate.
    Keeps every literal far below MSVC's per-literal limit."""
    out = []
    for line in data.split(b"\n"):
        s = []
        for b in line + b"\n":
            c = chr(b)
            if c == "\\":
                s.append("\\\\")
            elif c == '"':
                s.append('\\"')
            elif c == "\n":
                s.append("\\n")
            elif c == "\r":
                s.append("\\r")
            elif c == "\t":
                s.append("\\t")
            elif 32 <= b < 127:
                s.append(c)
            else:
                s.append("\\%03o" % b)
        out.append('\t"%s"' % "".join(s))
    # the loop added a "\n" the file did not have after its last line
    if data.endswith(b"\n"):
        out.pop()
    else:
        out[-1] = out[-1][:-3] + '"'
    return out


def generate():
    parts = [
        "/* hw_strings_data.h -- GENERATED by scripts/gen_hw_strings.py from",
        " * gamecode/res/{hw,siege}/strings.txt.  Do not edit; rerun the script.",
        " * Compiled-in fallback for Host_LoadHWStrings (GitHub #214). */",
        "",
    ]
    for gamedir, name in TABLES:
        path = os.path.join(ROOT, "gamecode", "res", gamedir, "strings.txt")
        with open(path, "rb") as f:
            data = f.read()
        parts.append("/* gamecode/res/%s/strings.txt, %d bytes */" % (gamedir, len(data)))
        parts.append("static const char %s[] =" % name)
        parts.extend(c_literal_lines(data))
        parts[-1] += ";"
        parts.append("")
    return "\n".join(parts)


def main():
    text = generate()
    if "--check" in sys.argv[1:]:
        try:
            cur = open(OUT, encoding="latin-1").read()
        except OSError:
            cur = None
        if cur != text:
            print("hw_strings_data.h is stale; run scripts/gen_hw_strings.py")
            return 1
        print("hw_strings_data.h matches gamecode/res")
        return 0
    with open(OUT, "w", encoding="latin-1", newline="\n") as f:
        f.write(text)
    print("wrote " + os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
