#!/usr/bin/env python3
"""
Extract entities of interest from a Hexen II `edicts` console dump.

The engine's `edicts` command prints every live entity with all its fields,
which is thousands of lines per dump.  This pulls out just the classnames you
care about and just the fields that usually matter, so several dumps taken at
different times can be eyeballed or diffed side by side.

Input is an engine stdout/qconsole.log containing one or more dumps, each
preceded by a marker line of the form `ZZZ<TAG>` (see headless-cfg.sh, which
generates a config that emits exactly those markers around `edicts` calls).
Sections tagged `PRE` or `DUMP*` are reported; anything else is skipped.

Usage:
  edict_pick.py <logfile> [classname,classname,...] [--fields f1,f2,...]

Examples:
  edict_pick.py run.log
  edict_pick.py run.log player,timebomb
  edict_pick.py run.log timebomb --fields origin,velocity,nextthink,think
"""
import argparse
import re
import sys

DEFAULT_CLASSES = ['player', 'stickmine', 'tripwire', 'proximity', 'timebomb']

DEFAULT_FIELDS = ['classname', 'origin', 'velocity', 'movetype', 'solid',
                  'v_angle', 'angles', 'nextthink', 'think', 'touch', 'owner',
                  'model', 'lifetime', 'dmg', 'avelocity', 'flags', 'health']

MARKER = re.compile(r'^ZZZ(\w+)\s*$', re.M)


def parse(text, want, fields):
    out = []
    # split() with one capture group yields [preamble, tag, body, tag, body, ...]
    sections = MARKER.split(text)
    it = iter(sections[1:])
    for tag, body in zip(it, it):
        if not tag.startswith('DUMP') and tag != 'PRE':
            continue
        rows = []
        for blk in body.split('\nEDICT '):
            m = re.search(r'^classname\s+(\S+)', blk, flags=re.M)
            if not m or (want and m.group(1) not in want):
                continue
            num = blk.split(':')[0].strip()
            got = {}
            for line in blk.splitlines()[1:]:
                parts = line.split(None, 1)
                if len(parts) == 2:
                    got[parts[0]] = parts[1].strip()
            rows.append((num, ' '.join('%s=%s' % (k, got[k])
                                       for k in fields if k in got)))
        out.append((tag, rows))
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(
        description='Extract entities of interest from an `edicts` console dump.')
    ap.add_argument('logfile')
    ap.add_argument('classes', nargs='?', default=','.join(DEFAULT_CLASSES),
                    help='comma-separated classnames, or "all" (default: %s)'
                         % ','.join(DEFAULT_CLASSES))
    ap.add_argument('--fields', default=','.join(DEFAULT_FIELDS),
                    help='comma-separated fields to print, in order')
    args = ap.parse_args(argv)

    try:
        with open(args.logfile, errors='replace') as f:
            text = f.read()
    except OSError as e:
        print('edict_pick: cannot read %s: %s' % (args.logfile, e), file=sys.stderr)
        return 2

    want = None if args.classes == 'all' else set(
        c for c in args.classes.split(',') if c)
    fields = [f for f in args.fields.split(',') if f]

    sections = parse(text, want, fields)
    if not sections:
        print('edict_pick: no ZZZ-tagged dump sections in %s '
              '(was the config generated by headless-cfg.sh?)' % args.logfile,
              file=sys.stderr)
        return 1
    for tag, rows in sections:
        print('=' * 20, tag, '=' * 20)
        for num, line in rows:
            print('  EDICT %s: %s' % (num, line))
        if not rows:
            print('  (no matching entities)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
