# EmbedShaders.cmake -- turn engine/shaders/*.glsl into a C header of string
# literals, resolving #include "..." along the way.
#
# Run in script mode:
#   cmake -DSHADER_DIR=<dir> -DOUT_FILE=<header> -P EmbedShaders.cmake
#
# Written in plain CMake rather than as a host tool on purpose: this has to run
# identically under the native, mingw-w64 and emscripten toolchains, and CMake
# is the one program all three are guaranteed to have.  A C bintoc would have to
# be cross-built for the host, which is exactly the kind of thing that works on
# one of those three and not the others.
#
# GLSL has no #include of its own (ARB_shading_language_include is not core and
# is not in GLSL ES at all), so the expansion happens here and the generated
# header holds the fully expanded text.  That also means glslangValidator and
# the GL driver see the same bytes.  uhexen2-p4ln.4.

if(NOT SHADER_DIR OR NOT OUT_FILE)
    message(FATAL_ERROR "EmbedShaders: SHADER_DIR and OUT_FILE are required")
endif()

file(GLOB SHADER_FILES "${SHADER_DIR}/*.glsl")
list(SORT SHADER_FILES)

set(GENERATED "/* Generated by engine/cmake/EmbedShaders.cmake -- do not edit.\n")
string(APPEND GENERATED " * Source of truth is engine/shaders/*.glsl. */\n\n")
string(APPEND GENERATED "#ifndef SHADERS_GEN_H\n#define SHADERS_GEN_H\n\n")

foreach(shader ${SHADER_FILES})
    get_filename_component(name "${shader}" NAME_WE)
    file(READ "${shader}" body)

    # Resolve includes.  Bounded rather than while(TRUE) so a cyclic include
    # fails the build instead of hanging it.
    foreach(pass RANGE 8)
        if(NOT body MATCHES "#include \"([^\"]+)\"")
            break()
        endif()
        set(incname "${CMAKE_MATCH_1}")
        if(NOT EXISTS "${SHADER_DIR}/${incname}")
            message(FATAL_ERROR "EmbedShaders: ${name} includes missing ${incname}")
        endif()
        file(READ "${SHADER_DIR}/${incname}" inctext)
        string(REPLACE "#include \"${incname}\"\n" "${inctext}" body "${body}")
    endforeach()
    if(body MATCHES "#include \"")
        message(FATAL_ERROR "EmbedShaders: ${name} has unresolved or cyclic includes")
    endif()

    # C string escaping, then one literal per source line so a shader compile
    # log's line numbers still mean something.
    string(REPLACE "\\" "\\\\" body "${body}")
    string(REPLACE "\"" "\\\"" body "${body}")
    string(REPLACE "\n" "\\n\"\n\t\"" body "${body}")

    string(APPEND GENERATED "static const char ${name}[] =\n\t\"${body}\";\n\n")
endforeach()

string(APPEND GENERATED "#endif /* SHADERS_GEN_H */\n")

# Only rewrite when the contents actually change, so a no-op regeneration does
# not force everything that includes the header to rebuild.
set(PREVIOUS "")
if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" PREVIOUS)
endif()
if(NOT PREVIOUS STREQUAL GENERATED)
    file(WRITE "${OUT_FILE}" "${GENERATED}")
    message(STATUS "EmbedShaders: wrote ${OUT_FILE}")
endif()
